"""Add incidents_bronze and telemetry_bronze tables

Revision ID: 2f55e135519e
Revises: 9fa5613a769f
Create Date: 2026-06-23 15:48:10.427892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f55e135519e'
down_revision: Union[str, Sequence[str], None] = '9fa5613a769f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('idx_maintenance_machine_time'), table_name='maintenance')
    op.drop_index(op.f('idx_maintenance_type'), table_name='maintenance')
    op.drop_table('maintenance')
    op.drop_index(op.f('idx_machine_line'), table_name='machine')
    op.drop_index(op.f('idx_machine_location'), table_name='machine')
    op.drop_table('machine')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_table('incidents')
    op.add_column('incidents_bronze', sa.Column('surchauffe', sa.String(), nullable=True))
    op.add_column('incidents_bronze', sa.Column('baisse_pression', sa.String(), nullable=True))
    op.add_column('incidents_bronze', sa.Column('vibration', sa.String(), nullable=True))
    op.add_column('incidents_bronze', sa.Column('bruit_mecanique', sa.String(), nullable=True))
    op.add_column('incidents_bronze', sa.Column('surconsommation', sa.String(), nullable=True))
    op.add_column('incidents_bronze', sa.Column('blocage_mecanique', sa.String(), nullable=True))
    op.add_column('incidents_bronze', sa.Column('alarme_capteur', sa.String(), nullable=True))
    op.add_column('incidents_bronze', sa.Column('arret_urgence', sa.String(), nullable=True))
    op.add_column('incidents_bronze', sa.Column('defaut_qualite', sa.String(), nullable=True))
    op.add_column('incidents_bronze', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents_bronze', 'comment')
    op.drop_column('incidents_bronze', 'defaut_qualite')
    op.drop_column('incidents_bronze', 'arret_urgence')
    op.drop_column('incidents_bronze', 'alarme_capteur')
    op.drop_column('incidents_bronze', 'blocage_mecanique')
    op.drop_column('incidents_bronze', 'surconsommation')
    op.drop_column('incidents_bronze', 'bruit_mecanique')
    op.drop_column('incidents_bronze', 'vibration')
    op.drop_column('incidents_bronze', 'baisse_pression')
    op.drop_column('incidents_bronze', 'surchauffe')
    op.create_table('incidents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('shift', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('machine_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('incidents_pkey'))
    )
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_table('machine',
    sa.Column('machine_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('commissioning_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('max_daily_capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_hourly_capacity_pieces', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('production_line', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('criticality', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("criticality::text = ANY (ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying]::text[])", name=op.f('machine_criticality_check')),
    sa.CheckConstraint('max_daily_capacity > 0', name=op.f('machine_max_daily_capacity_check')),
    sa.CheckConstraint('max_hourly_capacity_pieces > 0', name=op.f('machine_max_hourly_capacity_pieces_check')),
    sa.PrimaryKeyConstraint('machine_code', name=op.f('machine_pkey'))
    )
    op.create_index(op.f('idx_machine_location'), 'machine', ['location'], unique=False)
    op.create_index(op.f('idx_machine_line'), 'machine', ['production_line'], unique=False)
    op.create_table('maintenance',
    sa.Column('maintenance_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('machine_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('maintenance_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('maintenance_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('component', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('related_incident_id', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('duration_hours', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("maintenance_type::text = ANY (ARRAY['proactive'::character varying, 'reactive'::character varying]::text[])", name=op.f('maintenance_maintenance_type_check')),
    sa.CheckConstraint('duration_hours > 0::numeric', name=op.f('maintenance_duration_hours_check')),
    sa.ForeignKeyConstraint(['machine_code'], ['machine.machine_code'], name=op.f('maintenance_machine_code_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('maintenance_id', name=op.f('maintenance_pkey'))
    )
    op.create_index(op.f('idx_maintenance_type'), 'maintenance', ['maintenance_type'], unique=False)
    op.create_index(op.f('idx_maintenance_machine_time'), 'maintenance', ['machine_code', 'maintenance_at'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('machine_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('temperature_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pressure_bar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('voltage_mean_v', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rotation_mean_rpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pieces_produced', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_pkey'))
    )
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=False)
    # ### end Alembic commands ###
