"""Add machine and maintance tables in alembic model

Revision ID: b199a2b52651
Revises: 933137a56985
Create Date: 2026-07-06 12:59:36.350068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b199a2b52651'
down_revision: Union[str, Sequence[str], None] = '933137a56985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents_bronze',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('shift', sa.String(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('surchauffe', sa.String(), nullable=True),
    sa.Column('baisse_pression', sa.String(), nullable=True),
    sa.Column('vibration', sa.String(), nullable=True),
    sa.Column('bruit_mecanique', sa.String(), nullable=True),
    sa.Column('surconsommation', sa.String(), nullable=True),
    sa.Column('blocage_mecanique', sa.String(), nullable=True),
    sa.Column('alarme_capteur', sa.String(), nullable=True),
    sa.Column('arret_urgence', sa.String(), nullable=True),
    sa.Column('defaut_qualite', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('flag_ok', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_bronze_id'), 'incidents_bronze', ['id'], unique=False)
    op.create_table('machine',
    sa.Column('machine_code', sa.String(length=16), nullable=False),
    sa.Column('commissioning_date', sa.Date(), nullable=False),
    sa.Column('max_daily_capacity', sa.Integer(), nullable=False),
    sa.Column('max_hourly_capacity_pieces', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('production_line', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=16), nullable=False),
    sa.Column('criticality', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('machine_code')
    )
    op.create_index(op.f('ix_machine_location'), 'machine', ['location'], unique=False)
    op.create_index(op.f('ix_machine_production_line'), 'machine', ['production_line'], unique=False)
    op.create_table('telemetry_bronze',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('temperature_c', sa.String(), nullable=True),
    sa.Column('pressure_bar', sa.String(), nullable=True),
    sa.Column('voltage_mean_v', sa.String(), nullable=True),
    sa.Column('rotation_mean_rpm', sa.String(), nullable=True),
    sa.Column('pieces_produced', sa.String(), nullable=True),
    sa.Column('flag_ok', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_bronze_id'), 'telemetry_bronze', ['id'], unique=False)
    op.create_table('maintenance',
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('machine_code', sa.String(length=16), nullable=False),
    sa.Column('maintenance_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('maintenance_type', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('related_incident_id', sa.String(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['machine_code'], ['machine.machine_code'], ),
    sa.PrimaryKeyConstraint('maintenance_id')
    )
    op.create_index(op.f('ix_maintenance_machine_code'), 'maintenance', ['machine_code'], unique=False)
    op.create_index(op.f('ix_maintenance_maintenance_id'), 'maintenance', ['maintenance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_maintenance_id'), table_name='maintenance')
    op.drop_index(op.f('ix_maintenance_machine_code'), table_name='maintenance')
    op.drop_table('maintenance')
    op.drop_index(op.f('ix_telemetry_bronze_id'), table_name='telemetry_bronze')
    op.drop_table('telemetry_bronze')
    op.drop_index(op.f('ix_machine_production_line'), table_name='machine')
    op.drop_index(op.f('ix_machine_location'), table_name='machine')
    op.drop_table('machine')
    op.drop_index(op.f('ix_incidents_bronze_id'), table_name='incidents_bronze')
    op.drop_table('incidents_bronze')
    # ### end Alembic commands ###
