"""Add machine and maintance tables in alembic model

Revision ID: 933137a56985
Revises: 2f55e135519e
Create Date: 2026-06-23 17:53:46.211664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '933137a56985'
down_revision: Union[str, Sequence[str], None] = '2f55e135519e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('machine_code', sa.String(length=16), nullable=False),
    sa.Column('commissioning_date', sa.Date(), nullable=False),
    sa.Column('max_daily_capacity', sa.Integer(), nullable=False),
    sa.Column('max_hourly_capacity_pieces', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('production_line', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=16), nullable=False),
    sa.Column('criticality', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('machine_code')
    )
    op.create_index(op.f('ix_machine_location'), 'machine', ['location'], unique=False)
    op.create_index(op.f('ix_machine_production_line'), 'machine', ['production_line'], unique=False)
    op.create_table('maintenance',
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('machine_code', sa.String(length=16), nullable=False),
    sa.Column('maintenance_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('maintenance_type', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('related_incident_id', sa.String(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['machine_code'], ['machine.machine_code'], ),
    sa.PrimaryKeyConstraint('maintenance_id')
    )
    op.create_index(op.f('ix_maintenance_machine_code'), 'maintenance', ['machine_code'], unique=False)
    op.create_index(op.f('ix_maintenance_maintenance_id'), 'maintenance', ['maintenance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_maintenance_id'), table_name='maintenance')
    op.drop_index(op.f('ix_maintenance_machine_code'), table_name='maintenance')
    op.drop_table('maintenance')
    op.drop_index(op.f('ix_machine_production_line'), table_name='machine')
    op.drop_index(op.f('ix_machine_location'), table_name='machine')
    op.drop_table('machine')
    # ### end Alembic commands ###
